### PR TITLE
Ep add post

### PR DESCRIPTION
**Pull request by ember-parr**
# Description
Given the user is viewing the Post Management menu
When they select the option to add a post
Then they should be prompted to enter the new post's title, url and publish date
Then they should be presented with a list of Authors to choose from (This should behave as other selection list do throughout the app)
Then they should be presented with a list of Blogs to choose from (This should behave as other selection list do throughout the app)
Then the new post should be saved to the database

Fixes issue #15 

## Type of change
Please delete options that are not relevant.
- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Testing Instructions
No changes needed to test 

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by terraroush** [comment]
this pull request is super easy to follow. thanks for that! the only thing i see missing, based on the above description of the issue, is that the user should be able to add the published date.
one other consideration is to change the name of "New Post" to "Add Post" for consistency's sake. Blog, Author and Journal say "Add..."
i'd say you could merge as is and make a new ticket for adding the publishing date, or implement that now and update the pr.

**Comment by ember-parr** [comment]
Terra's requests have been completed & added to this pull request.

**Review by terraroush — APPROVED** [review]
SOLID

**Comment by j0verton** [comment]
working great, also approve!

**Pull request merged**
